version: '3'

services:
  nestbank_app:
    build: .
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - nestbank_db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - bubble
  nestbank_db:
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest
    networks:
      - bubble
networks:
  bubble:
    external: true
